# Generated by Django 5.1.2 on 2024-12-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('workshop', 'Workshop'), ('concert', 'Concert'), ('sports', 'Sports Event'), ('community', 'Community Event')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tickets', models.PositiveIntegerField()),
                ('payment', models.CharField(choices=[('credit-card', 'Credit Card'), ('debit-card', 'Debit Card'), ('paypal', 'Khalti'), ('upi', 'Esewa')], max_length=50)),
            ],
        ),
    ]
