# Generated by Django 5.1.4 on 2024-12-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('dropdown_option', models.CharField(choices=[('Workshop', 'Workshop'), ('Concert', 'Concert'), ('Sports Event', 'Sports Event'), ('Community Events', 'Community Events')], max_length=50)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
