# Generated by Django 5.1.4 on 2024-12-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_formsubmission_alter_usersubmission_dropdown_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
