# Generated by Django 5.1.4 on 2024-12-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_delete_ticket_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formsubmission',
            new_name='contactform',
        ),
    ]
