# Generated by Django 5.1.4 on 2024-12-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_rename_formsubmission_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubmission',
            new_name='ticketform',
        ),
    ]
