# Generated by Django 5.1.4 on 2025-01-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0009_event_event_date_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketform',
            name='payment_approved',
            field=models.BooleanField(default=False),
        ),
    ]
