# Generated by Django 5.1.4 on 2025-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
