# Generated by Django 5.1.4 on 2025-01-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0012_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
    ]
