# Generated by Django 5.1.4 on 2025-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0013_remove_ticket_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketform',
            name='payment_approved',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
